### ISSUE TITLE
Street View visor

### ISSUE THREAD

**Issue by manudona92** [manudona92/MapantES#16]
Sabiendo que Agustín seguro está al tanto de esto. Cómo mejorar la herramienta Street View ya que en el visor "Beta" (que está genial por cierto), la mayoría de veces te lleva a ninguna parte, aun haciendo zoom en la carretera que tiene Street View. Hay muchos visores que ya lo incorporan, abajo uno de ellos. 

Un ejemplo es el visor del Instituto Cartográfico Valenciano: https://visor.gva.es/visor/

Por cierto, para mi es una de las cosas que más utilizo, y más se utilizaría, ya que ves el bosque o terreno más facilmente.

**Comment by agustincaballero** [comment]
No entiendo muy bien a qué te refieres; en el visor beta nuestro, si le picas en un punto y luego al enlace Street View, te lleva al sitio. Si no hay street view, te sale pantalla en negro. Pero creo que eso lo hace igual lo del visor valenciano, ¿no?
Hasta donde yo sé, no se puede saber a priori si en un punto determinado hay o no street view.

**Comment by manudona92** [comment]
Mea culpa. 

Me acabo de enterar como funciona. Pulso sobre un punto (se abre también la ventanita del PNG), y luego pulso en STREET VIEW. Funciona perfectamente. 

Visor de GeoEuskadi (https://www.geo.euskadi.eus/s69-bisorea/es/x72aGeoeuskadiWAR/index.jsp) también lo tiene con icono + arrastrar a la carretera. Lógicamente, parece que no tienen como GMaps que ves en azul aquellos sitios que tienen imgan de Street View. Arrastrando parece más intuitivo, pero si se explica, de la forma que esta ahora está bien también.

**Comment by manudona92** [comment]
Respecto a Street View, es una herramienta súper útil. Como dije anteriormente, una forma más intuitiva es con un logo de "arrastre" a la carretera del visor 
Otro ejemplo más intuitivo del visor de  GRAFCAN: https://visor.grafcan.es/visorweb/

![image](https://user-images.githubusercontent.com/76484741/107875480-74f63200-6ec0-11eb-970e-7602c21782d8.png)
