### ISSUE TITLE
Aerogeneradores GID 377034645

### ISSUE THREAD

**Issue by manudona92** [manudona92/MapantES#39]
Según hablamos, era mejor quitar el verde privado de los aerogeneradores. 

El símbolo puntual de torre está bien, pero el área privada se sigue renderizando

![image](https://user-images.githubusercontent.com/76484741/107533182-f6974880-6bbe-11eb-8d40-2cfdec4cb2cc.png)

**Comment by agustincaballero** [comment]
Ya está corregida esa cuadrícula. Si observáis alguna más, ponedla aquí

**Comment by manudona92** [comment]
En el Hierro: GID 102133078
