### ISSUE TITLE
Crucetas negras - Clasificación suelo

### ISSUE THREAD

**Issue by manudona92** [manudona92/MapantES#42]
Aparecen en 1 de cada 10 o 20 cuadrículas. Puede que haya +1000 en total en Galicia Oeste y la verdad es que se me pasó porque ni en Oia ni en las otras zonas test lo vi. 

Son crucetas negras, con cortados. Mi teoría es que proviene de la clasificación del suelo que emplea el IGN, y que no utiliza buffer. Por eso en los extremos de las tiles de 2x2 km crea esos baches. Tendria que verlo en profundidad y ver si metiendo un lasnoise solo a esas cuadriculas mejoraría. Para eso, necesitariamos una herramienta, tipo la de los noruegos de "Reportar tile" y así saber que cuadrículas reprocesariamos. Creo que cuando hagamos el geoTIF se verá mejor el patrón de estas crucetas negras, y una vez sacado, valorar si realmente vale la pena reprocesarlas o no...porque quizás no valga la pena 

![image](https://user-images.githubusercontent.com/76484741/108621796-1e937100-7435-11eb-9f23-f8603fe990ea.png)

**Comment by manudona92** [comment]
Efectivamente, al 99% es un problema originario de los datos LAZ. En los bordes de Tile el suelo no está tan bien clasificado

![image](https://user-images.githubusercontent.com/76484741/108636212-1d3d6500-7484-11eb-869e-e465501af849.png)

A partir de aquí podemos ver: 
- Reprocesar esas tiles con crucetas con los nuevos datos de Galicia Oeste REFINADOS (subidos recientemente al CDG)
- Reprocesar esas tiles con lasnoise. Tendriamos que hacer una prueba con 20-30 tiles para ver si crea algun tipo de cambio en curva de nivel o cortados significativo
- Dejarlo como está y no preocuparnos (pasará en otros lotes también)

Para los dos primeros Agustín necesitaria meter una herramienta de REPORTE TILES para localizar las tiles afectadas (+500 seguro)

**Comment by JesusMorenoJ** [comment]
Galicia va con una clasificación diferente en la nueva actualización del CdD, supuestamente mucho mejor. 
Me da la impresión que vamos a tener que reprocesar todo Galicia. En cuanto tengamos el shapefile hacemos pruebas en zonas localizadas con problemas.
