### ISSUE TITLE
Piedras renderizadas???

### ISSUE THREAD

**Issue by jarufe** [manudona92/MapantES#52]
Estaba comprobando el material descargado de una cuadrícula cualquiera. Al importar en OOM el fichero dotknolls.dxf me fijé que las piedras no están renderizadas. Seguramente lo hablamos en su día y se llegó a esa conclusión. ¿Es así?

**Comment by manudona92** [comment]
Correcto. Por experiencia, +80% de los _dotknolls_ que KP extrae son erróneos. Esto depende directamente de la clasificación del suelo, además de que el lote tenga suficiente densidad para penetrar y que justo caiga en la piedra (normalmente la separación entre puntos es de 1-1.5 m, así que para que se detectado tiene que ser una piedra con un diámetro considerable y si está en masa boscosa pues que caiga en retorno intermedio). Yo he visto muchos _dotknolls_ que salen muy mal sobre todo en terrenos de encinares, carrascas, bosques muy densos...y es por la mala clasificación del suelo. 

Puede ser que en un lote con buena densidad (+1  pts/m2), terreno abierto y con buena clasificación de suelo, el archivo _dotknolls_ salga con buena precisión, ya sea para piedra o montículo.
