### ISSUE TITLE
NE Alicante - Cambio de huso 30-31 BTN25

### ISSUE THREAD

**Issue by manudona92** [manudona92/MapantES#59]
A la zona que está en huso 31 de Alicante (la parte noreste) le faltan varios elementos por renderizar. Quizá lo mejor es re renderizar toda esa parte con las capas que faltan. Las capas de la BTN25 que he visto que faltan son: 

- Autovía
- Carreteras
- Caminos
- Vía de tren

Creo que a lo mejor se nos olvidó importar toda esta info o reconvertirla de huso 31 a 30.

**Comment by agustincaballero** [comment]
Sí, había un error en el cliente, creo que está corregido. Pronto pondré todas esas cuadriculas a renderizar de nuevo.

**Comment by agustincaballero** [comment]
Esta zona ya está renderizada correctamente (en la capa Debug). Echadle un vistazo y cerrad este tema si lo veis bien.
